version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Main docker
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Dependencies
  - package-ecosystem: npm
    directory: "/dependencies"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Doc
  - package-ecosystem: npm
    directory: "/docs/record"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: "/docs/record"
    schedule:
      interval: daily
      time: "02:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
