DISABLE:
  - COPYPASTE # too many false-positives
  - CSS
  - JAVASCRIPT
  - TYPESCRIPT

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - REPOSITORY_SEMGREP
  - RUST_CLIPPY
  - SPELL_CSPELL

# Override default config files
DOCKERFILE_HADOLINT_CONFIG_FILE: .hadolint.yaml
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_FLAKE8_CONFIG_FILE: setup.cfg
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: pyproject.toml
RUBY_RUBOCOP_CONFIG_FILE: .rubocop.yml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

# Config
JSON_V8R_FILTER_REGEX_EXCLUDE: composer.json
