version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint
      - build

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.4.5
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache alpine-sdk nodejs npm bash
      - run: make bootstrap build test-lite
