version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint
      - build

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.6.6
    steps:
      - checkout
      - run: find .config -type f -exec sh -c 'ln -s "$0" "$(basename "$0")"' {} \; # TODO: Remove
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  build:
    docker:
      - image: docker:24.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache alpine-sdk nodejs npm bash
      - run: make bootstrap build test
