#!/bin/bash
# Custom push hook for dockerhub
# When git tag like v1.2.3 appers
# This pushes docker tags :1, :1.2, :1.2.3, :latest

tag_original="${DOCKER_REPO}:${DOCKER_TAG}"
printf 'Original tag: %s\n' "${tag_original}"
docker tag "${IMAGE_NAME}" "${tag_original}"
docker push "${tag_original}"

if [ "${DOCKER_TAG}" = 'dev' ]; then
    exit 0
fi

tag_minor="${DOCKER_REPO}:${DOCKER_TAG%.*}"
printf 'Minor tag: %s\n' "${tag_minor}"
docker tag "${IMAGE_NAME}" "${tag_minor}"
docker push "${tag_minor}"

tag_major="${DOCKER_REPO}:${DOCKER_TAG%.*.*}"
printf 'Major tag: %s\n' "${tag_major}"
docker tag "${IMAGE_NAME}" "${tag_major}"
docker push "${tag_major}"

tag_latest="${DOCKER_REPO}:latest"
printf 'Latest tag: %s\n' "${tag_latest}"
docker tag "${IMAGE_NAME}" "${tag_latest}"
docker push "${tag_latest}"
