extends: default

rules:
  # require 0-1 space when non-empty: "[xyz]" or "[ xyz ]"
  # and 0 spaces when empty: "[]"
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # disallow leading "---" and trailing "..."
  document-end:
    present: false
  document-start:
    present: false

  line-length:
    max: 250

  # prettier does only 1 space between content and comment
  comments:
    min-spaces-from-content: 1

  # few CI services (github actions, travis) use "on" as a key meaning "when"
  truthy:
    check-keys: false
