name: Dependabot auto-merge

permissions:
  pull-requests: write
  contents: write

on: pull_request_target

jobs:
  dependabot:
    name: Dependabot automerge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Prepare metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable automerge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
