name: Deploy

permissions: read-all

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Docker tags
        uses: docker/metadata-action@v4.6.0
        id: tags
        with:
          images: |
            matejkosiarcik/planckpng
          tags: |
            type=edge,branch=main
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.7.0

      - name: Debug logs
        run: |
          printf "Platforms:\n%s\n" "${{ steps.buildx.outputs.platforms }}"
          printf "Tags:\n%s\n" "${{ steps.tags.outputs.tags }}"

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish
        uses: docker/build-push-action@v4.1.1
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
