name: Lint

on:
  pull_request:

jobs:
  mega-linter:
    name: Mega-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Mega Linter
        uses: nvuillam/mega-linter@v4.46.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          # Rest of the config is in /.mega-linter.yml
