name: Build

permissions: read-all

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64
          push: false
          tags: matejkosiarcik/millipng:dev
