name: Deploy

permissions: read-all

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Docker tags
        uses: docker/metadata-action@v4.5.0
        id: tags
        with:
          images: |
            matejkosiarcik/millipng
          tags: |
            type=raw,value=dev,enable=${{ github.event_name == 'push' }}
            type=raw,value=latest,enable=${{ github.event_name == 'push tag' }}
            type=semver,pattern={{major}},enable=${{ github.event_name == 'push tag' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'push tag' }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ github.event_name == 'push tag' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker tags
        run: echo ${{ steps.tags.outputs.tags }}

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
